<?php
/**
 * @file
 * Install hooks for the Status Report module.
 */

/**
 * Implements hook_install().
 *
 * Set the modules weight above that of the domain theme module to ensure that
 * Rubik will always be the priority theme on status pages.
 */
function status_report_install() {
  db_update('system')
    ->fields(array('weight' => 5))
    ->condition('type', 'module')
    ->condition('name', 'status_report')
    ->execute();
}
